---
# defaults file for wordpress
wp_install_dir: "/var/www/html"
wp_document_root_dir: "{{ wp_install_dir }}/wordpress" 
wp_db_name: "{{ wp_mysql_db }}"
wp_db_user: "{{ wp_mysql_user }}"
wp_db_password: "{{ wp_mysql_password }}"
wp_db_host: "{{ wp_mysql_host }}"
wp_db_charset: "utf8"
wp_table_prefix: 'wp_'
wp_db_collate: ''
wp_debug: true
wp_admin_email: "admin@wordpress.com"
wp_server_name: ""
