Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-22.04"
  
  # Configs for slave1
  config.vm.define :slave1 do |slave1|
  	# Configs for virtual machine entry in Oracle VM VirtualBox
        slave1.vm.provider :virtualbox do |vb_config|
            vb_config.name = "slave1"
            vb_config.memory = "2096"
        end
        # Terminal name
        slave1.vm.hostname = "slave1"
        # IP address to access from host machine
        slave1.vm.network "private_network", ip: "192.168.56.4"
  end
  
  # Configs for slave2
  config.vm.define :slave2 do |slave2|
  	# Configs for virtual machine entry in Oracle VM VirtualBox
        slave2.vm.provider :virtualbox do |vb_config|
            vb_config.name = "slave2"
            vb_config.memory = "2096"
        end
        # Terminal name
        slave2.vm.hostname = "slave2"
        # IP address to access from host machine
        slave2.vm.network "private_network", ip: "192.168.56.5"
  end
  
end
